# Generated by Django 3.1.3 on 2020-12-14 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250, verbose_name='Input Value')),
            ],
            options={
                'verbose_name': 'InputLang Value',
                'verbose_name_plural': 'InputLang Value',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('short', models.CharField(max_length=3, verbose_name='Short Name')),
            ],
            options={
                'verbose_name': 'Languages',
                'verbose_name_plural': 'Languages',
                'ordering': ['short'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Group')),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_parent', to='locales.translation')),
            ],
        ),
        migrations.CreateModel(
            name='TranslationValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translationValue_key', to='locales.translation')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translationValue_value', to='locales.inputlang')),
            ],
        ),
        migrations.CreateModel(
            name='TextLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='Input Value')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textLang_lang', to='locales.lang')),
            ],
            options={
                'verbose_name': 'TextLang Value',
                'verbose_name_plural': 'TextLang Value',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Location Name')),
                ('type', models.CharField(choices=[('country', 'Country'), ('county', 'County'), ('town', 'Town'), ('district', 'District')], default='county', max_length=8, verbose_name='Location Type')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_parent', to='locales.location')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Location',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='inputlang',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputLang_lang', to='locales.lang'),
        ),
    ]
