# Generated by Django 3.1.3 on 2020-12-14 04:42

import attach.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[800, 600], upload_to=attach.models.image_folder)),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Alt')),
                ('direction', models.CharField(default='h', max_length=1, verbose_name='Direction')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
